Add type hints.
This fixes the two errors:

```
axelrod/fingerprint.py:444: error: Function "numpy.array" is not valid as a type
22
axelrod/fingerprint.py:444: note: Perhaps you need "Callable[...]" or a callback protocol?
23
Found 1 error in 1 file (checked 1 source file)
```

and:

```
axelrod/strategies/ann.py:125: error: Incompatible types in assignment (expression has type "ndarray", variable has type "List[int]")
34
Found 1 error in 1 file (checked 1 source file)
```

note that in `fingerprint.py` I'm using the `ArrayType` type but that
when I tried to use that in `ann.py` a lot of other things broke.